DotnetSquad/metrodata-idle-management-system

API/Models/BaseEntity.cs

chore: change namespace BaseEntity.cs

---

API/Models/Role.cs

feat: create role model

---

Client/Controllers/HomeController.cs
Client/Views/Home/Error403.cshtml

feat: create 403 error page

---

Client/Views/Account/Login.cshtml
Client/Views/Account/Register.cshtml
Client/Views/Shared/_LayoutRegister.cshtml

chore: minor updated in login and register

---

API/Controllers/CompanyController.cs
API/Controllers/EmployeeInterviewController.cs
API/Controllers/RoleController.cs
API/Program.cs
API/Services/EmployeeInterviewService.cs

feat: CRUD for employee interview

---

API/Controllers/ProjectController.cs
API/Program.cs
API/Services/ProjectService.cs

feat: create CRUD project

---

API/Controllers/EmployeeProjectController.cs
API/Services/EmployeeProjectService.cs

feat: CRUD for employee project

---

API/DataTransferObjects/Accounts/AccountDtoCreate.cs

feat: add guid in account dto create

---

API/Controllers/AccountController.cs
API/Program.cs
API/Services/AccountService.cs

feat: create CRUD for account

---

API/Controllers/PlacementController.cs
API/Program.cs
API/Services/PlacementService.cs

feat: create CRUD for placement

---

API/Controllers/AccountRoleController.cs
API/Program.cs
API/Services/AccountRoleService.cs

feat: CRUD for account role

---

API/Controllers/ProfileController.cs
API/Program.cs
API/Services/ProfileService.cs

feat: CRUD for profile

---

API/Controllers/CompanyController.cs

feat: change message response company controller

---

API/API.csproj
API/Program.cs
API/Utilities/Validations/Roles/RoleValidatorCreate.cs
API/Utilities/Validations/Roles/RoleValidatorGet.cs
API/Utilities/Validations/Roles/RoleValidatorUpdate.cs

feat: fluent validation role dtos

---

API/Utilities/Validations/AccountRoles/AccountRoleValidatorCreate.cs
API/Utilities/Validations/AccountRoles/AccountRoleValidatorGet.cs
API/Utilities/Validations/AccountRoles/AccountRoleValidatorUpdate.cs

- [] Print statements are deleted

feat: create fluent validations account role dtos

---

API/Utilities/Validations/Accounts/AccountValidatorCreate.cs
API/Utilities/Validations/Accounts/AccountValidatorGet.cs
API/Utilities/Validations/Accounts/AccountValidatorUpdate.cs

feat: create fluent validations account dtos

---

API/Utilities/Validations/Placements/PlacementValidatorCreate.cs
API/Utilities/Validations/Placements/PlacementValidatorGet.cs
API/Utilities/Validations/Placements/PlacementValidatorUpdate.cs

feat: create fluent validation placement dtos

---

API/Utilities/Validations/Projects/ProjectValidatorCreate.cs
API/Utilities/Validations/Projects/ProjectValidatorGet.cs
API/Utilities/Validations/Projects/ProjectValidatorUpdate.cs

feat: create fluent validations project dtos

---

API/Utilities/Validations/Grades/GradeValidatorCreate.cs
API/Utilities/Validations/Grades/GradeValidatorGet.cs
API/Utilities/Validations/Grades/GradeValidatorUpdate.cs

feat: creat fluent validations grade dtos

---

API/Utilities/Validations/Companies/CompanyValidatorCreate.cs
API/Utilities/Validations/Companies/CompanyValidatorGet.cs
API/Utilities/Validations/Companies/CompanyValidatorUpdate.cs

feat: fluent validation company dtos

---

API/Utilities/Validations/EmployeeProjects/EmployeeProjectValidatorCreate.cs
API/Utilities/Validations/EmployeeProjects/EmployeeProjectValidatorGet.cs
API/Utilities/Validations/EmployeeProjects/EmployeeProjectValidatorUpdate.cs

feat: create fluent validations employeeproject dtos

---

API/Utilities/Validations/Jobs/JobValidatorCreate.cs
API/Utilities/Validations/Jobs/JobValidatorGet.cs
API/Utilities/Validations/Jobs/JobValidatorUpdate.cs

feat: create fluent validations job dtos

---

API/Utilities/Validations/Profiles/ProfileValidatorCreate.cs
API/Utilities/Validations/Profiles/ProfileValidatorGet.cs
API/Utilities/Validations/Profiles/ProfileValidatorUpdate.cs

feat: create fluent validations profile dtos

---

API/Utilities/Validations/Interviews/InterviewValidatorCreate.cs
API/Utilities/Validations/Interviews/InterviewValidatorGet.cs
API/Utilities/Validations/Interviews/InterviewValidatorUpdate.cs

feat: create fluent validation interview dtos

---

API/Utilities/Enums/StatusInterviewEnum.cs

feat: add pending statusinterview enum

---

API/Contracts/IEmployeeRepository.cs
API/Repositories/BaseRepository.cs
API/Repositories/EmployeeRepository.cs
API/Utilities/Validations/Employees/EmployeeValidatorCreate.cs
API/Utilities/Validations/Employees/EmployeeValidatorGet.cs
API/Utilities/Validations/Employees/EmployeeValidatorUpdate.cs

feat: create fluent validation employee dtos

---

API/Utilities/Validations/EmployeeInterviews/EmployeeInterviewValidatorCreate.cs
API/Utilities/Validations/EmployeeInterviews/EmployeeInterviewValidatorGet.cs
API/Utilities/Validations/EmployeeInterviews/EmployeeInterviewValidatorUpdate.cs

feat: create fluent validations employee interview dtos

---

API/Utilities/Handlers/HashingHandler.cs

feat: create hashing handler

---

API/API.csproj
API/Contracts/IAccountRoleRepository.cs
API/Contracts/IEmployeeRepository.cs
API/Contracts/ITokenHandler.cs
API/Controllers/AccountController.cs
API/DataTransferObjects/Accounts/AccountDtoLogin.cs
API/Program.cs
API/Repositories/AccountRoleRepository.cs
API/Repositories/EmployeeRepository.cs
API/Services/AccountService.cs
API/Utilities/Handlers/TokenHandler.cs

feat: create login feature

---

API/Contracts/IEmailHandler.cs
API/Controllers/AccountController.cs
API/DataTransferObjects/Accounts/AccountDtoForgotPassword.cs
API/Program.cs
API/Services/AccountService.cs
API/Utilities/Handlers/EmailHandler.cs

feat: create forgot password feature

---

API/Contracts/IEmployeeRepository.cs
API/Contracts/IRoleRepository.cs
API/Controllers/AccountController.cs
API/DataTransferObjects/Accounts/AccountDtoRegister.cs
API/Repositories/EmployeeRepository.cs
API/Repositories/RoleRepository.cs
API/Services/AccountService.cs
API/Utilities/Handlers/GenerateHandler.cs
API/Utilities/Validations/Accounts/AccountValidatorRegister.cs

feat: create register feature

---

API/Program.cs

feat: add configure swagger

---

API/Program.cs

feat: create CORS configuration

---

Client/Contracts/IBaseRepository.cs
Client/Contracts/IRoleRepository.cs
Client/Controllers/RoleController.cs
Client/Program.cs
Client/Repositories/BaseRepository.cs
Client/Repositories/RoleRepository.cs
Client/Utilities/Handlers/ResponseHandler.cs
Client/Views/Role/Index.cshtml

feat: create view datatable role

---

Client/Contracts/IEmployeeRepository.cs
Client/Controllers/EmployeeController.cs
Client/Program.cs
Client/Repositories/EmployeeRepository.cs
Client/Views/Employee/Index.cshtml

feat: create view datatable employee

---

Client/Client.csproj
Client/Contracts/IGradeRepository.cs
Client/Controllers/GradeController.cs
Client/Program.cs
Client/Repositories/GradeRepository.cs
Client/Views/Grade/Index.cshtml

feat: create view data table grade

---

Client/Views/Employee/Index.cshtml
Client/Views/Shared/_LayoutDashboard.cshtml
Client/wwwroot/js/site.js

feat: implement data table

---

Client/Client.csproj
Client/Contracts/ICompanyRepository.cs
Client/Controllers/CompanyController.cs
Client/Program.cs
Client/Repositories/CompanyRepository.cs
Client/Views/Company/Index.cshtml

feat: create view datatable company

---

Client/Contracts/IPlacementRepository.cs
Client/Controllers/PlacementController.cs
Client/Program.cs
Client/Repositories/PlacementRepository.cs
Client/Views/Placement/Index.cshtml

feat: create view data table placement

---

Client/Client.csproj
Client/Contracts/IProfileRepository.cs
Client/Controllers/ProfileController.cs
Client/Program.cs
Client/Repositories/ProfileRepository.cs
Client/Views/Profile/Index.cshtml

feat: create view data table profile

---

Client/Contracts/IInterviewRepository.cs
Client/Controllers/InterviewController.cs
Client/Program.cs
Client/Repositories/InterviewRepository.cs
Client/Views/Interview/Index.cshtml

feat: create view data table interview

---

Client/Controllers/RoleController.cs
Client/Views/Role/Create.cshtml
Client/Views/Role/Index.cshtml

feat: create view create role feature

---

Client/Controllers/GradeController.cs
Client/Views/Grade/Create.cshtml
Client/Views/Grade/Index.cshtml

feat: create view create grade feature

---

Client/Controllers/CompanyController.cs
Client/Views/Company/Create.cshtml
Client/Views/Company/Index.cshtml
Client/Views/Role/Create.cshtml

feat: create view create company

---

API/DataTransferObjects/Employees/EmployeeDtoCreate.cs
API/Services/EmployeeService.cs
API/Utilities/Validations/Employees/EmployeeValidatorCreate.cs
Client/Controllers/EmployeeController.cs
Client/DataTransferObjects/Employees/EmployeeDtoCreate.cs
Client/Views/Employee/Create.cshtml
Client/Views/Employee/Index.cshtml

feat: create viewcreate employee

---

Client/Controllers/ProfileController.cs
Client/Views/Profile/Create.cshtml
Client/Views/Profile/Index.cshtml

feat: create viewcreate profile

---

Client/Controllers/ProjectController.cs
Client/Views/Project/Create.cshtml
Client/Views/Project/Index.cshtml

feat: create view create project feature

---

Client/Controllers/InterviewController.cs
Client/Views/Interview/Create.cshtml
Client/Views/Interview/Index.cshtml

feat: create view create interview feature

---

Client/Controllers/JobController.cs
Client/Views/Job/Create.cshtml
Client/Views/Job/Index.cshtml

feat: create view create job feature

---

Client/Controllers/RoleController.cs
Client/Repositories/BaseRepository.cs
Client/Views/Role/Index.cshtml
Client/Views/Role/Update.cshtml

feat: create view edit role

---

Client/Controllers/CompanyController.cs
Client/Views/Company/Index.cshtml
Client/Views/Company/Update.cshtml

feat: create view update company

---

Client/Controllers/ProfileController.cs
Client/Views/Profile/Index.cshtml
Client/Views/Profile/Update.cshtml

feat: create view update profile

---

Client/Controllers/InterviewController.cs
Client/Views/Interview/Index.cshtml
Client/Views/Interview/Update.cshtml

feat: create view update interview

---

Client/Controllers/ProjectController.cs
Client/Views/Project/Index.cshtml
Client/Views/Project/Update.cshtml

feat: create view update project

---

Client/Controllers/JobController.cs
Client/Views/Job/Index.cshtml
Client/Views/Job/Update.cshtml

feat: create view update job

---

Client/Controllers/CompanyController.cs
Client/Repositories/BaseRepository.cs
Client/Views/Company/Index.cshtml

feat: create delete controller company

---

API/Utilities/Validations/Employees/EmployeeValidatorUpdate.cs
Client/Controllers/EmployeeController.cs
Client/Views/Employee/Index.cshtml
Client/Views/Employee/Update.cshtml

feat: create view update employee

---

Client/Controllers/EmployeeController.cs

feat: create delete controller employee

---

Client/Controllers/ProfileController.cs
Client/Views/Profile/Index.cshtml

feat: create delete controller profile

---

Client/Controllers/GradeController.cs
Client/Views/Grade/Index.cshtml
Client/Views/Grade/Update.cshtml

- [] Test is created/updated. If not, specify from whom it is confirmed that unit test is not needed.

feat: create delete controller grade

---

Client/Controllers/InterviewController.cs
Client/Views/Role/Index.cshtml

Reverts DotnetSquad/metrodata-idle-management-system#326

Revert "feat: create delete controller role"

---

Client/Controllers/ProjectController.cs
Client/Views/Project/Index.cshtml

feat: create delete controller project

---

Client/Controllers/JobController.cs
Client/Views/Job/Index.cshtml

feat: create delete controller job

---

Client/Controllers/InterviewController.cs
Client/Views/Interview/Index.cshtml

feat: create delete interview feature

---

Client/Controllers/PlacementController.cs
Client/Views/Placement/Index.cshtml

feat: create delete placement feature

---

Client/Controllers/RoleController.cs
Client/Views/Role/Index.cshtml

feat: create delete role feature

---

Client/Contracts/IAccountRepository.cs
Client/Controllers/AccountController.cs
Client/Program.cs
Client/Repositories/AccountRepository.cs
Client/Repositories/BaseRepository.cs
Client/Views/Account/Register.cshtml

feat: create register feature client

---

Client/Contracts/IAccountRepository.cs
Client/Repositories/AccountRepository.cs
Client/Repositories/BaseRepository.cs

fix: fix bug not implement in account repository

---

API/Controllers/AccountController.cs
API/Controllers/AccountRoleController.cs
API/Controllers/CompanyController.cs
API/Controllers/EmployeeController.cs
API/Controllers/EmployeeInterviewController.cs
API/Controllers/EmployeeProjectController.cs
API/Controllers/GradeController.cs
API/Controllers/InterviewController.cs
API/Controllers/JobController.cs
API/Controllers/PlacementController.cs
API/Controllers/ProfileController.cs
API/Controllers/ProjectController.cs
API/Controllers/RoleController.cs
API/Program.cs
API/Utilities/Enums/RoleLevel.cs

feat: enable authorization in api

---

Client/Contracts/IAccountRepository.cs
Client/Controllers/AccountController.cs
Client/Repositories/AccountRepository.cs
Client/Views/Account/ChangePassword.cshtml
Client/Views/Account/ForgotPassword.cshtml
Client/appsettings.json

feat: create change password feature client

---

Client/Views/Shared/_LayoutDashboard.cshtml

feat: create sidebar for each index controller entity

---

API/Controllers/AccountController.cs
API/Controllers/AccountRoleController.cs
API/Controllers/CompanyController.cs
API/Controllers/EmployeeController.cs
API/Controllers/EmployeeInterviewController.cs
API/Controllers/EmployeeProjectController.cs
API/Controllers/GradeController.cs
API/Controllers/InterviewController.cs
API/Controllers/JobController.cs
API/Controllers/PlacementController.cs
API/Controllers/ProfileController.cs
API/Controllers/ProjectController.cs
API/Controllers/RoleController.cs
API/DataTransferObjects/Grades/GradeDtoGenerateScore.cs
API/DataTransferObjects/Grades/GradeDtoUpdateGenerateScore.cs
API/Services/GradeService.cs
API/Utilities/Enums/RoleLevelEnum.cs
API/Utilities/Handlers/GenerateHandler.cs
API/Utilities/Validations/Grades/GradeValidatorCreateGenerate.cs
Client/Contracts/IGradeRepository.cs
Client/Controllers/GradeController.cs
Client/DataTransferObjects/Grades/GradeDtoGenerateScore.cs
Client/Program.cs
Client/Repositories/GradeRepository.cs
Client/Utilities/Enums/RoleLevelEnum.cs
Client/Views/Grade/Create.cshtml
Client/Views/Grade/Index.cshtml
Client/Views/Grade/Update.cshtml

feat: create grade level total score generate

---

API/Controllers/CompanyController.cs
Client/Controllers/CompanyController.cs
Client/Controllers/EmployeeController.cs
Client/Controllers/GradeController.cs
Client/Controllers/InterviewController.cs
Client/Controllers/JobController.cs
Client/Controllers/PlacementController.cs
Client/Controllers/ProfileController.cs
Client/Controllers/ProjectController.cs
Client/Controllers/RoleController.cs
Client/Views/Home/Error401.cshtml
Client/Views/Home/Error403.cshtml
Client/Views/Home/Error404.cshtml
Client/Views/Interview/Create.cshtml
Client/Views/Interview/Update.cshtml
Client/Views/Role/Create.cshtml

feat: authorization client controller

---

API/Controllers/AccountController.cs
API/Controllers/AccountRoleController.cs
API/Controllers/CompanyController.cs
API/Controllers/EmployeeController.cs
API/Controllers/EmployeeInterviewController.cs
API/Controllers/EmployeeProjectController.cs
API/Controllers/GradeController.cs
API/Controllers/InterviewController.cs
API/Controllers/JobController.cs
API/Controllers/PlacementController.cs
API/Controllers/ProfileController.cs
API/Controllers/ProjectController.cs
API/Controllers/RoleController.cs
API/Utilities/Enums/RoleLevelEnum.cs
Client/Controllers/CompanyController.cs
Client/Controllers/EmployeeController.cs
Client/Controllers/GradeController.cs
Client/Controllers/InterviewController.cs
Client/Controllers/JobController.cs
Client/Controllers/PlacementController.cs
Client/Controllers/ProfileController.cs
Client/Controllers/ProjectController.cs
Client/Controllers/RoleController.cs
Client/Utilities/Enums/RoleLevelEnum.cs

feat: add administator role and make full access to application

---

Client/Views/Company/Index.cshtml
Client/Views/Employee/Index.cshtml
Client/Views/Grade/Index.cshtml
Client/Views/Interview/Index.cshtml
Client/Views/Job/Index.cshtml
Client/Views/Placement/Index.cshtml
Client/Views/Profile/Index.cshtml
Client/Views/Project/Index.cshtml
Client/Views/Role/Index.cshtml

feat: beautify edit and delete buttons in client

---

Client/Views/Project/Create.cshtml
Client/Views/Project/Index.cshtml
Client/Views/Shared/_LayoutDashboard.cshtml
Client/wwwroot/js/site.js

feat: create sweet alert delete project

---

Client/Views/Profile/Index.cshtml

feat: create sweet alert delete profile

---

Client/Views/Interview/Index.cshtml

feat: create sweet alert delete interview

---

Client/Views/Role/Index.cshtml

feat: implement sweet alert in delete confirmation role

---

Client/Views/Job/Index.cshtml

feat: create sweet alert delete job

---

Client/Views/Grade/Index.cshtml

feat: implement sweet alert in delete confirmation grade

---

Client/Views/Placement/Index.cshtml

feat: implement sweet alert in delete confirmation placement

---

Client/Views/Company/Index.cshtml
Client/wwwroot/js/site.js

feat: implement sweet alert in delete confirmation company

---

Client/Controllers/AccountController.cs
Client/Views/Shared/_LayoutDashboard.cshtml

feat: create feature logout

---

API/DataTransferObjects/Accounts/AccountDtoCreate.cs
API/DataTransferObjects/Accounts/AccountDtoUpdate.cs

feat: enable hashing password when create and update account

---

Client/Views/Employee/Index.cshtml

feat: implement sweet alert in delete confirmation employee

---

Client/Controllers/PlacementController.cs
Client/Views/Placement/Index.cshtml

refactor: display company and employee name in placement index

---

Client/Controllers/JobController.cs
Client/Views/Job/Index.cshtml

refactor: display company name in job index

---

Client/Views/Shared/_LayoutLandingPage.cshtml
Client/wwwroot/Arsha/assets/css/style.css

refactor: adjust the landing page according to the application

---

Client/Views/Shared/_LayoutDashboard.cshtml

feat: authorize sidebar view in layout dashboard

---

Client/Views/Dashboard/Index.cshtml
Client/Views/Shared/_LayoutDashboard.cshtml

feat: beautify navbar in client

---

Client/Controllers/InterviewController.cs

feat: handle response handler from API in interview controller client

---

Client/Controllers/PlacementController.cs

feat: handle response handler from API in placement controller client

---

Client/Controllers/RoleController.cs

feat: handle response handler from API in role controller client

---

Client/wwwroot/js/site.js

feat: Scroll - horizontal data table feature

---

Client/Controllers/EmployeeController.cs

feat: response handler from api in employee controller

---

Client/Controllers/ProfileController.cs

feat: response handler from api in profile controller

---

Client/Controllers/CompanyController.cs

feat: response handler from api in company controller

---

Client/Views/Shared/_LayoutDashboard.cshtml

feat: fix logo in navbar

---

Client/Client.csproj
Client/Views/Company/Index.cshtml
Client/Views/Shared/_LayoutDashboard.cshtml

feat: add toastr in company index

---

Client/Views/Profile/Index.cshtml

feat: add toastr in profile index

---

Client/Views/Employee/Index.cshtml
Client/Views/Role/Index.cshtml

feat: add toastr in employee index client

---

Client/Controllers/RoleController.cs
Client/Views/Role/Index.cshtml

feat: add toastr in role index client

---

Client/Views/Placement/Index.cshtml

feat: add toastr in placement index client

---

Client/Views/Company/Index.cshtml
Client/Views/Employee/Index.cshtml
Client/Views/Grade/Index.cshtml
Client/Views/Interview/Index.cshtml
Client/Views/Job/Index.cshtml
Client/Views/Placement/Index.cshtml
Client/Views/Profile/Index.cshtml
Client/Views/Project/Index.cshtml
Client/Views/Role/Index.cshtml
Client/Views/Shared/_LayoutDashboard.cshtml

feat: handle toastr in client

---

Client/Views/Dashboard/Index.cshtml

feat: create view statistic employees dashboard

---

Client/Controllers/ProjectController.cs

feat: handle response handler from API in project controller client

---

Client/Controllers/GradeController.cs

feat: handle response handler from API in grade controller client

---

Client/Controllers/JobController.cs

feat: handle response handler from API in job controller client

---

API/Services/AccountService.cs

feat: add Guid in claims JWT Token

---

Client/Views/Shared/_LayoutDashboard.cshtml

feat: show name in navbar based on who is login

---

API/Services/EmployeeService.cs

feat: add-resume-when-create-employee

---

API/Services/AccountService.cs
Client/Controllers/ProfileController.cs
Client/Views/Profile/Details.cshtml
Client/Views/Shared/_LayoutDashboard.cshtml

feat: create feature profile

---

API/Contracts/IEmployeeRepository.cs
API/Controllers/DashboardController.cs
API/DataTransferObjects/Dashboards/DashboardsDtoGetStatus.cs
API/Program.cs
API/Repositories/EmployeeRepository.cs
API/Services/DashboardService.cs

feat: create end point for statistic employees

---

Client/Contracts/IDashboardRepository.cs
Client/Controllers/DashboardController.cs
Client/DataTransferObjects/Dashboards/DashboardsDtoGetStatus.cs
Client/Program.cs
Client/Repositories/DashboardRepository.cs
Client/Views/Dashboard/Index.cshtml

feat: make view dashboard data get from api

---

.gitignore

feat: Update .gitignore

---

API/Services/AccountService.cs
Client/Client.csproj
Client/Controllers/ProfileController.cs
Client/Views/Profile/Details.cshtml

feat: create view profile details from api

---

Client/Controllers/AccountController.cs

feat: handle response from API in account controller client

---

Client/Controllers/ProfileController.cs
Client/Views/Profile/Details.cshtml

feat: create update profile feature

---

API/Controllers/EmployeeController.cs
API/Services/EmployeeService.cs
Client/Contracts/IAccountRoleRepository.cs
Client/Contracts/IEmployeeRepository.cs
Client/Controllers/AccountRoleController.cs
Client/Controllers/EmployeeController.cs
Client/Program.cs
Client/Repositories/AccountRoleRepository.cs
Client/Repositories/EmployeeRepository.cs
Client/Views/AccountRole/Create.cshtml
Client/Views/AccountRole/Index.cshtml

[Screencast from 08-01-2023 01:00:38 AM.webm](https://github.com/DotnetSquad/metrodata-idle-management-system/assets/49428466/ee3ffcb6-691f-4e49-b510-66f2040ab945)

feat: create role management feature

---

API/Controllers/EmployeeProjectController.cs
Client/Contracts/IEmployeeProjectRepository.cs
Client/Controllers/EmployeeProjectController.cs
Client/Program.cs
Client/Repositories/EmployeeProjectRepository.cs
Client/Views/EmployeeProject/Create.cshtml
Client/Views/EmployeeProject/Index.cshtml
Client/Views/EmployeeProject/Update.cshtml
Client/Views/Shared/_LayoutDashboard.cshtml

feat: create crud employee project client

---

API/Controllers/EmployeeInterviewController.cs
Client/Contracts/IEmployeeInterviewRepository.cs
Client/Controllers/EmployeeInterviewController.cs
Client/Program.cs
Client/Repositories/EmployeeInterviewRepository.cs
Client/Views/EmployeeInterview/Create.cshtml
Client/Views/EmployeeInterview/Index.cshtml
Client/Views/EmployeeInterview/Update.cshtml
Client/Views/Shared/_LayoutDashboard.cshtml

feat: create crud employee interview client

---

Client/Contracts/IDashboardRepository.cs
Client/Controllers/DashboardController.cs
Client/Controllers/JobController.cs
Client/DataTransferObjects/Dashboards/DashboardDtoGetInterviewStatus.cs
Client/Repositories/DashboardRepository.cs
Client/Views/Dashboard/Index.cshtml
Client/Views/Job/Create.cshtml

feat: create dashboard for status interview data get from API

---

Client/Repositories/DashboardRepository.cs
Client/Views/Dashboard/Index.cshtml
Client/Views/Shared/_LayoutDashboard.cshtml

feat: delete unused card in dashboard

---

API/Services/EmployeeService.cs
Client/Views/Shared/_LayoutDashboard.cshtml

fix: bug add employee role management

---

API/Controllers/EmployeeController.cs
API/Services/EmployeeService.cs

feat: create end point get employee by email

---

Client/Views/Shared/_LayoutDashboard.cshtml

feat: show profile in sidebar and only authorize for admin

---

Client/Controllers/AccountRoleController.cs

feat: show toastr in crud role management

---

Client/Views/Employee/Create.cshtml
Client/Views/Employee/Update.cshtml
Client/Views/Profile/Details.cshtml

feat: change all input datetime to input date

---

Client/Controllers/CompanyController.cs
Client/Controllers/DashboardController.cs
Client/Controllers/EmployeeController.cs
Client/Controllers/EmployeeInterviewController.cs
Client/Controllers/EmployeeProjectController.cs
Client/Controllers/GradeController.cs
Client/Controllers/InterviewController.cs
Client/Controllers/JobController.cs
Client/Controllers/PlacementController.cs
Client/Controllers/ProfileController.cs
Client/Controllers/ProjectController.cs
Client/Controllers/RoleController.cs
Client/Views/Shared/_LayoutDashboard.cshtml

feat: handle active sidebar base on what is open

---

API/Controllers/EmployeeController.cs
API/Services/EmployeeProjectService.cs
API/Services/EmployeeService.cs
Client/Contracts/IEmployeeRepository.cs
Client/Controllers/EmployeeProjectController.cs
Client/Repositories/EmployeeRepository.cs
Client/Views/EmployeeProject/Create.cshtml
Client/Views/EmployeeProject/Index.cshtml
Client/Views/Project/Create.cshtml
Client/Views/Project/Index.cshtml

feat: create view employee project based project guid

---

Client/Controllers/EmployeeProjectController.cs

chore: add switch handling create

---

Client/Views/Shared/_LayoutDashboard.cshtml

feat: change logic authorization in sidebar

---

Client/Views/Role/Create.cshtml
Client/Views/Role/Index.cshtml
Client/Views/Role/Update.cshtml

feat: set view role table in client

---

Client/Views/Grade/Create.cshtml
Client/Views/Grade/Index.cshtml
Client/Views/Grade/Update.cshtml

feat: set view grade in client

---

Client/Views/Grade/Create.cshtml
Client/Views/Grade/Update.cshtml
Client/Views/Project/Create.cshtml
Client/Views/Project/Index.cshtml
Client/Views/Project/Update.cshtml

feat: set view project table in client

---

Client/Views/Company/Create.cshtml
Client/Views/Company/Index.cshtml
Client/Views/Company/Update.cshtml

feat: set the view of the company table in the client

---

Client/Views/Company/Create.cshtml
Client/Views/Company/Index.cshtml
Client/Views/Placement/Create.cshtml
Client/Views/Placement/Index.cshtml
Client/Views/Placement/Update.cshtml

feat: set the view of the placement table in the client

---

Client/Controllers/EmployeeProjectController.cs
Client/Views/EmployeeProject/Create.cshtml
Client/Views/EmployeeProject/Index.cshtml
Client/Views/EmployeeProject/Update.cshtml

feat: set view employee project table client

---

Client/Views/Profile/Create.cshtml
Client/Views/Profile/Index.cshtml
Client/Views/Profile/Update.cshtml

feat: set the view of the profile table in the client

---

Client/Views/Interview/Create.cshtml
Client/Views/Interview/Index.cshtml
Client/Views/Interview/Update.cshtml

feat: set the view of the interview table in the client

---

API/Controllers/DashboardController.cs
API/DataTransferObjects/EmployeeInterviews/EmployeeInterviewDtoCreate.cs
API/DataTransferObjects/EmployeeInterviews/EmployeeInterviewDtoGet.cs
API/DataTransferObjects/EmployeeInterviews/EmployeeInterviewDtoUpdate.cs
API/Services/DashboardService.cs
API/Services/EmployeeInterviewService.cs

feat: add status approval in employee interview api

---

Client/Views/Dashboard/Index.cshtml

feat: create top client dashboard

---

Client/DataTransferObjects/EmployeeInterviews/EmployeeInterviewDtoCreate.cs
Client/DataTransferObjects/EmployeeInterviews/EmployeeInterviewDtoGet.cs
Client/DataTransferObjects/EmployeeInterviews/EmployeeInterviewDtoUpdate.cs
Client/Repositories/DashboardRepository.cs
Client/Utilities/Enums/StatusApprovalEnum.cs
Client/Views/EmployeeInterview/Create.cshtml
Client/Views/EmployeeInterview/Index.cshtml
Client/Views/EmployeeInterview/Update.cshtml

feat: set view employee interview in client

---

API/Controllers/EmployeeProjectController.cs
API/DataTransferObjects/EmployeeProjects/EmployeeProjectDtoCreate.cs
API/DataTransferObjects/EmployeeProjects/EmployeeProjectDtoGet.cs
API/DataTransferObjects/EmployeeProjects/EmployeeProjectDtoUpdate.cs
API/Services/EmployeeProjectService.cs
API/Services/ProjectService.cs
Client/Contracts/IEmployeeProjectRepository.cs
Client/Controllers/EmployeeProjectController.cs
Client/Controllers/ProjectController.cs
Client/DataTransferObjects/EmployeeProjects/EmployeeProjectDtoGet.cs
Client/Repositories/EmployeeProjectRepository.cs
Client/Utilities/Enums/StatusApprovalEnum.cs
Client/Views/EmployeeProject/Index.cshtml
Client/Views/Project/Index.cshtml
Client/Views/Shared/_LayoutDashboard.cshtml

feat:  POV trainer in employee project

---

Client/Controllers/EmployeeProjectController.cs
Client/Views/EmployeeProject/Index.cshtml

feat: create reject feature in employee project

---

Client/Controllers/GradeController.cs
Client/Views/Grade/Details.cshtml
Client/Views/Grade/Index.cshtml
Client/Views/Shared/_LayoutDashboard.cshtml

feat: create grade details employee

---

API/Controllers/EmployeeController.cs
API/Controllers/GradeController.cs
Client/Controllers/DashboardController.cs
Client/Controllers/GradeController.cs
Client/Views/Dashboard/Index.cshtml

feat: show grade in dashboard

---

API/Program.cs
API/Utilities/Handlers/EmailHandler.cs

feat: use gmail to send otp forgot password

---

API/Controllers/CompanyController.cs
API/Controllers/EmployeeController.cs
API/Controllers/JobController.cs
API/Controllers/RoleController.cs
Client/Controllers/EmployeeProjectController.cs
Client/Controllers/ProjectController.cs
Client/Views/EmployeeProject/Create.cshtml
Client/Views/EmployeeProject/Index.cshtml
Client/Views/EmployeeProject/Update.cshtml
Client/Views/Project/Create.cshtml
Client/Views/Project/Index.cshtml
Client/Views/Shared/_LayoutDashboard.cshtml

feat: beautify project management feature

---

API/Controllers/EmployeeController.cs
API/Services/EmployeeService.cs

feat: create endpoint get employee by job and exclude by job

---

Client/Controllers/FAQController.cs
Client/Views/FAQ/Index.cshtml
Client/Views/Shared/_LayoutDashboard.cshtml

feat: create FAQ feature

---

API/Controllers/CompanyController.cs
API/Controllers/EmployeeJobController.cs
API/Controllers/JobController.cs
Client/Contracts/IEmployeeJobRepository.cs
Client/Contracts/IEmployeeRepository.cs
Client/Controllers/EmployeeJobController.cs
Client/Controllers/JobController.cs
Client/Repositories/EmployeeJobRepository.cs
Client/Repositories/EmployeeRepository.cs
Client/Views/EmployeeJob/Create.cshtml
Client/Views/EmployeeJob/Index.cshtml
Client/Views/Job/Index.cshtml
Client/Views/Shared/_LayoutDashboard.cshtml

feat: create request employee job feature

---

API/Services/EmployeeProjectService.cs

feat: if manager approve, then change status employee to working

---

API/Services/EmployeeService.cs

feat: must idle employee for request employee project and employee job

---

API/Services/EmployeeService.cs
Client/Views/Grade/Index.cshtml

delete grade and profile column while delete employee

---

Client/Controllers/ProfileController.cs
Client/DataTransferObjects/Profiles/EmployeeProfileDtoGet.cs
Client/Repositories/ProfileRepository.cs
Client/Views/Profile/Details.cshtml

feat: create update employee on my profile feature

---

API/Contracts/IPlacementRepository.cs
API/Repositories/PlacementRepository.cs
API/Services/EmployeeJobService.cs

feat: approval and reject behavior feature

---

API/Services/AccountService.cs

feat: change clamis jwt only send guid and roles

---

Client/Controllers/DashboardController.cs
Client/DataTransferObjects/Employees/EmployeeDtoGet.cs
Client/DataTransferObjects/Profiles/EmployeeProfileDtoGet.cs
Client/Views/Profile/Details.cshtml
Client/Views/Shared/_LayoutDashboard.cshtml

feat: change full name in dashboard to get from database

---

Client/Views/Profile/Details.cshtml

feat: delete setting account and change password in profile detail

---

API/Services/AccountService.cs
Client/Views/AccountRole/Index.cshtml
Client/Views/Shared/_LayoutDashboard.cshtml

feat: show NIK in role management

---

Client/Controllers/AccountController.cs
Client/Utilities/Handlers/ResponseHandler.cs

feat: handle fluent validation

---

API/Contracts/IPlacementRepository.cs
API/Repositories/PlacementRepository.cs
API/Services/EmployeeJobService.cs
Client/Views/Placement/Index.cshtml

feat: add accepted employee from employeejob to placement

---

Client/Views/Grade/Index.cshtml

feat: set autorization for manager

---

API/DataTransferObjects/Employees/EmployeeDtoCreate.cs
API/DataTransferObjects/Employees/EmployeeDtoGet.cs
API/DataTransferObjects/Employees/EmployeeDtoUpdate.cs
API/DataTransferObjects/Profiles/ProfileDtoCreate.cs
API/DataTransferObjects/Profiles/ProfileDtoGet.cs
API/DataTransferObjects/Profiles/ProfileDtoUpdate.cs
API/Migrations/20230805101211_add-coloumn-photo-profile.Designer.cs
API/Migrations/20230805101211_add-coloumn-photo-profile.cs
API/Migrations/20230805122805_change-coloumn-profileguid-and-gradeguid.Designer.cs
API/Migrations/20230805122805_change-coloumn-profileguid-and-gradeguid.cs
API/Models/Employee.cs
API/Models/Profile.cs
API/Services/AccountService.cs
Client/Client.csproj
Client/Controllers/ProfileController.cs
Client/DataTransferObjects/Profiles/EmployeeProfileDtoGet.cs
Client/DataTransferObjects/Profiles/ProfileDtoCreate.cs
Client/DataTransferObjects/Profiles/ProfileDtoGet.cs
Client/DataTransferObjects/Profiles/ProfileDtoUpdate.cs
Client/Program.cs
Client/Utilities/Handlers/ResponseHandler.cs
Client/Views/Profile/Details.cshtml
Client/Views/Shared/_LayoutDashboard.cshtml

feat: handle photo profile

---

API/Controllers/EmployeeController.cs
API/Controllers/ProfileController.cs
Client/Controllers/ProfileController.cs
Client/Views/Profile/Details.cshtml

feat: update profile for role trainer, manager, hr

---

Client/Controllers/ProfileController.cs
Client/Views/Profile/Details.cshtml

feat: bug upload photo is required

---

API/DataTransferObjects/EmployeeJobs/EmployeeJobDtoCreate.cs
API/DataTransferObjects/EmployeeJobs/EmployeeJobDtoGet.cs
API/DataTransferObjects/EmployeeJobs/EmployeeJobDtoUpdate.cs
API/Migrations/20230805151736_change-type-interview-guid.Designer.cs
API/Migrations/20230805151736_change-type-interview-guid.cs
API/Models/EmployeeJob.cs
API/Services/EmployeeJobService.cs

feat: create interview when create employee job

---

API/Controllers/DashboardController.cs
API/DataTransferObjects/Dashboards/DashboardDtoGetClient.cs
API/Services/DashboardService.cs

feat: create end point for 5 top client

---

Client/Controllers/EmployeeProjectController.cs
Client/Controllers/ProjectController.cs
Client/Views/Profile/Details.cshtml
Client/Views/Project/Update.cshtml
Client/Views/Shared/_LayoutDashboard.cshtml

feat: bug update project management not trainer

---

Client/Controllers/AccountController.cs

fix: NullReferenceException

---

API/Services/AccountService.cs
API/Services/EmployeeService.cs
API/Utilities/Validations/Profiles/ProfileValidatorCreate.cs

fix: Failed executing DbCommand

---

Client/Views/Employee/Index.cshtml

feat: delete employee for column grade and profile

---

API/Controllers/CompanyController.cs
API/Controllers/EmployeeController.cs
API/Controllers/InterviewController.cs
Client/Controllers/CompanyController.cs
Client/Controllers/EmployeeJobController.cs
Client/Controllers/InterviewController.cs
Client/Views/Company/Create.cshtml
Client/Views/EmployeeJob/Index.cshtml
Client/Views/Interview/Index.cshtml
Client/Views/Job/Index.cshtml
Client/Views/Shared/_LayoutDashboard.cshtml

feat: change role approval for employee job from manager to hr

---

API/Controllers/EmployeeJobController.cs
Client/DataTransferObjects/EmployeeJobs/EmployeeJobDtoCreate.cs
Client/DataTransferObjects/EmployeeJobs/EmployeeJobDtoGet.cs
Client/DataTransferObjects/EmployeeJobs/EmployeeJobDtoUpdate.cs

fix: add employee in employee job client

---

Client/Views/AccountRole/Index.cshtml
Client/Views/Company/Index.cshtml
Client/Views/Employee/Index.cshtml
Client/Views/EmployeeJob/Index.cshtml
Client/Views/EmployeeProject/Index.cshtml
Client/Views/Grade/Index.cshtml
Client/Views/Interview/Index.cshtml
Client/Views/Job/Index.cshtml
Client/Views/Placement/Index.cshtml
Client/Views/Profile/Index.cshtml
Client/Views/Project/Index.cshtml
Client/Views/Role/Index.cshtml

feat: create tooltip in button

---

API/Controllers/DashboardController.cs
API/Services/DashboardService.cs
Client/Repositories/DashboardRepository.cs
Client/Views/EmployeeJob/Index.cshtml

feat: add status approval view dashboard

---

API/DataTransferObjects/Dashboards/DashboardDtoGetClient.cs
API/Services/DashboardService.cs
Client/Contracts/IDashboardRepository.cs
Client/Controllers/DashboardController.cs
Client/DataTransferObjects/Dashboards/DashboardDtoGetClient.cs
Client/Repositories/DashboardRepository.cs
Client/Views/Dashboard/Index.cshtml

Reverts DotnetSquad/metrodata-idle-management-system#599

Revert "feat: create top client dashboard"
